StartupEvents.registry("block", event => {
    const MODID = "tse:"
    ////event.create(MODID + "primitive_blast_furnace_bricks")
    ////    //.textureAll(MODID + "block/primitive_blast_furnace_bricks")
    ////    .requiresTool(true)
    ////    .soundType("stone")
    ////    .tagBlock("minecraft:mineable/pickaxe")
    ////event.create(MODID + "blast_furnace_bricks")
    ////    //.textureAll(MODID + "block/blast_furnace_bricks")
    ////    .requiresTool(true)
    ////    .soundType("stone")
    ////    .tagBlock("minecraft:mineable/pickaxe")
    ////event.create(MODID + "blast_furnace_vent","cardinal")
    ////    .requiresTool(true)
    ////    .soundType("stone")
    ////    .tagBlock("minecraft:mineable/pickaxe")
    ////event.create(MODID + "advanced_blast_furnace_vent","cardinal")
    ////    .requiresTool(true)
    ////    .soundType("stone")
    ////    .tagBlock("minecraft:mineable/pickaxe")
    event.create(MODID + "andesite_machine")
        //.model(MODID + 'block/andesite_machine')
        .hardness(2.0)
        .tagBlock("minecraft:mineable/pickaxe")
        .tagBlock("minecraft:mineable/axe")
})
