const $SoundEvents = Java.loadClass('net.minecraft.sounds.SoundEvents')
const $ParticleTypes = Java.loadClass('net.minecraft.core.particles.ParticleTypes')

StartupEvents.registry("fluid", event => {
    const MODID = "tse:"
    // const reg = (id, type, color) => {
    //     if(type == "thin") {
    //         event.create(MODID + id, "thin")
    //             .tint(color)
    //             .type(type => type
    //                 .renderType(3)
    //                 .stillTexture('kubejs:block/thin_fluid_still')
    //                 .flowingTexture('kubejs:block/thin_fluid_flow')
    //                 .fallDistanceModifier(0)
    //                 .addDripstoneDripping(1, $ParticleTypes.DRIPPING_DRIPSTONE_WATER, 'minecraft:water_cauldron', $SoundEvents.POINTED_DRIPSTONE_DRIP_WATER)
    //             )
    //     } else {
    //         event.create(MODID + id, "thick")
    //             .tint(color)
    //             .slopeFindDistance(2)
    //             .type(type => type
    //                 .renderType(0)
    //                 .stillTexture('kubejs:block/thick_fluid_still')
    //                 .flowingTexture('kubejs:block/thick_fluid_flow')
    //                 .canSwim(false)
    //                 .canDrown(false)
    //                 .density(3000)
    //                 .viscosity(6000)
    //                 .addDripstoneDripping(1, $ParticleTypes.DRIPPING_DRIPSTONE_LAVA, 'minecraft:lava_cauldron', $SoundEvents.POINTED_DRIPSTONE_DRIP_LAVA)
    //             )
    //     }
    // }
    const reg = (id, type, color) => {
        if(type == "thin") {
            event.create(MODID + id, "thin")
                //.translationKey("fluid.tse." + id)
                //.formattedDisplayName("Test")
                .noBlock()
                .tint(color)
                .type(type => type
                    .renderType(3)
                    .stillTexture('kubejs:block/thin_fluid_still')
                    .flowingTexture('kubejs:block/thin_fluid_flow')
                    .fallDistanceModifier(0)
                    .addDripstoneDripping(1, $ParticleTypes.DRIPPING_DRIPSTONE_WATER, 'minecraft:water_cauldron', $SoundEvents.POINTED_DRIPSTONE_DRIP_WATER)
                )
        } else {
            event.create(MODID + id, "thick")
                //.translationKey("fluid.tse." + id)
                //.formattedDisplayName("Test")
                .noBlock()
                .tint(color)
                .slopeFindDistance(2)
                .type(type => type
                    .renderType(0)
                    .stillTexture('kubejs:block/thick_fluid_still')
                    .flowingTexture('kubejs:block/thick_fluid_flow')
                    .canSwim(false)
                    .canDrown(false)
                    .density(3000)
                    .viscosity(6000)
                    .addDripstoneDripping(1, $ParticleTypes.DRIPPING_DRIPSTONE_LAVA, 'minecraft:lava_cauldron', $SoundEvents.POINTED_DRIPSTONE_DRIP_LAVA)
                )
        }
    }
    reg("liquid_unprocessed_sulfurated_rubber", "thick", 0x4F4644)
    reg("soul_alcohol", "thin", 0x4A362D)
    reg("recycled_echo_liquid", "thin", 0x082A34)
    reg("dirty_lubricant", "thin", 0xB66616)
    //reg("demagnetized_magnetic_carrier", )
    //reg("magnetized_magnetic_carrier",)
    reg("liquid_steel", "thick", 0xFF7700)
    reg("sulfuric_acid", "thin", 0xB69E16)
    reg("oxygen", "thin", 0x1785FF)
    reg("air", "thin", 0xFEFEFE)
    reg("hydrogen", "thin", 0x17FFE0)
    reg("pulp", "thick", 0xDDB179)
    reg("methanol", "thin", 0xDDDDDD)
    reg("chlorine", "thin", 0x2DA41D)
    //reg("abyss", )
    reg("sulfuric_refinery_gas", "thin", 0xE9E9E9)
    reg("sulfuric_naphtha", "thin", 0xEAC972)
    reg("sulfuric_light_oil", "thin", 0xF9F322)
    reg("sulfuric_heavy_oil", "thin", 0xD3CE1E)
    reg("refinery_gas", "thin", 0xE9E9E9)
    reg("naphtha", "thin", 0xEAC972)
    reg("light_oil", "thin", 0xF9F322)
    reg("heavy_oil", "thin", 0xD3CE1E)
    reg("dirty_steam", "thick", 0xEEEEEE)
    reg("bitumen", "thick", 0x180D3C)
    reg("processed_crude", "thick", 0x222222)
    reg("purified_creosote", "thin", 0x714627)
    reg("steam_cracked_refinery_gas", "thin", 0xE9E9E9)
    reg("ethylene", "thin", 0xF1F1F1)
    reg("caminite", "thick", 0xAAAAAA)
})
