StartupEvents.registry("item", event => {
    const MODID = "tse:"
    
    const dust = (id, color) => {
        event.create(MODID + id)
            .parentModel("tse:item/dust_base")
            .texture("tse:item/dust_base")
            .color(0, color)
    }

    //* Coins
    event.create(MODID + "copper_coin")
    event.create(MODID + "compressed_iron_coin")
    event.create(MODID + "gold_coin")

    event.create(MODID + "amethyst_dust")
    event.create(MODID + "quartz_dust")
    
    event.create(MODID + "andesite_mechanism")
    event.create(MODID + "incomplete_andesite_mechanism", "create:sequenced_assembly")
    event.create(MODID + "andesite_alloy_plate")
    event.create(MODID + "sealed_mechanism")
    event.create(MODID + "incomplete_sealed_mechanism", "create:sequenced_assembly")
    event.create(MODID + "carved_rose_quartz")
    event.create(MODID + "incomplete_carved_rose_quartz", "create:sequenced_assembly")
    event.create(MODID + "ember_mechanism")
    event.create(MODID + "incomplete_ember_mechanism", "create:sequenced_assembly")
    event.create(MODID + "unprocessed_sulfurated_rubber")
    event.create(MODID + "sulfurated_rubber")
    event.create(MODID + "echo_shard_plate")
    event.create(MODID + "echo_mechanism")
    event.create(MODID + "incomplete_echo_mechanism", "create:sequenced_assembly")
    event.create(MODID + "echo_catalyst")
    event.create(MODID + "ineffective_echo_catalyst")
    event.create(MODID + "advanced_ember_mechanism")
    event.create(MODID + "incomplete_advanced_ember_mechanism", "create:sequenced_assembly")
    event.create(MODID + "advanced_sealed_mechanism")
    event.create(MODID + "incomplete_advanced_sealed_mechanism", "create:sequenced_assembly")
    event.create(MODID + "iron_ingot_with_echo_impurity")
    event.create(MODID + "duplicating_echo_shard", "create:sequenced_assembly")
    event.create(MODID + "paper_circuit_base")
    event.create(MODID + "incomplete_empty_pcb",'create:sequenced_assembly')
    event.create(MODID + "resistor")
    event.create(MODID + "incomplete_pcb",'create:sequenced_assembly')
    event.create(MODID + "plate_iron_compressed")
    event.create(MODID + "menril_mechanism")
    event.create(MODID + "incomplete_menril_mechanism", "create:sequenced_assembly")
    event.create(MODID + "incomplete_variable_transformer_output", "create:sequenced_assembly")
    event.create(MODID + "incomplete_variable_transformer_input", "create:sequenced_assembly")
    event.create(MODID + "caminite_capacitor_packet")
    event.create(MODID + "carbon_rod")
    event.create(MODID + "spark_plug")
    event.create(MODID + "lead_monoxide")
    event.create(MODID + "lead_dioxide")
    event.create(MODID + "lead_chloride")
    event.create(MODID + "red_lead")
    event.create(MODID + "lead_nitrate")
    event.create(MODID + "sodium_sulfide")
    event.create(MODID + "sodium_sulfate")
    event.create(MODID + "calcium_sulfide")
    event.create(MODID + "calcium_hydroxide")
    event.create(MODID + "sodium_carbonate")
    event.create(MODID + "lead_carbonate")

    event.create(MODID + "incomplete_diesel_engine", "create:sequenced_assembly")
})