StartupEvents.registry("item", event => {
    const MODID = "tse:"
    ////event.create(MODID + "flint_axe", "axe")
    ////    .tier("wood")
    ////event.create(MODID + "flint_pickaxe", "pickaxe")
    ////    .tier("wood")
    ////event.create(MODID + "flint_hatchet", "axe")
    ////    .maxDamage(15)
    ////event.create(MODID + "primitive_blast_furnace_brick")
    ////event.create(MODID + "blast_furnace_brick")
    ////event.create(MODID + "reforged_stone")
    ////event.create(MODID + "flint_dust")
    ////event.create(MODID + "granite_dust")
    ////event.create(MODID + "mortar")
    ////event.create(MODID + "clay_brick")
    ////event.create(MODID + "unfired_pig_iron")
    ////event.create(MODID + "coal_dust")
    ////event.create(MODID + "pig_iron_ingot")
    ////event.create(MODID + "pig_iron_pickaxe", "pickaxe")
    ////    .maxDamage(150)
    ////    .tier("stone")
    ////event.create(MODID + "pig_iron_hammer")
    ////event.create(MODID + "limestone_dust")
    ////event.create(MODID + "hard_brick")
    ////event.create(MODID + "hard_brick_dust")
    ////event.create(MODID + "compound_clay_ball")
    ////event.create(MODID + "unfired_copper")
    ////event.create(MODID + "bastard_zinc_ingot")
    ////event.create(MODID + "bastard_copper_ingot")
    ////event.create(MODID + "bastard_brass_ingot")
    ////event.create(MODID + "brass_mortar")
    ////event.create(MODID + "pig_iron_sheet")
    ////event.create(MODID + "terracotta_dust")
    ////event.create(MODID + "nether_brick_dust")
    ////event.create(MODID + "fireclay")
    ////event.create(MODID + "advanced_blast_furnace_brick")
    ////event.create(MODID + "raw_iron_dust")
    ////event.create(MODID + "lime_dust")
    ////event.create(MODID + "raw_iron_mixture")
    ////event.create(MODID + "zinc_dust")
    ////event.create(MODID + "brass_dust")
    //* Coins
    event.create(MODID + "copper_coin")
    event.create(MODID + "compressed_iron_coin")
    event.create(MODID + "gold_coin")

    event.create(MODID + "amethyst_dust")
    event.create(MODID + "quartz_dust")
    
    event.create(MODID + "andesite_mechanism")
    event.create(MODID + "incomplete_andesite_mechanism", "create:sequenced_assembly")
    event.create(MODID + "andesite_alloy_plate")
    event.create(MODID + "sealed_mechanism")
    event.create(MODID + "incomplete_sealed_mechanism", "create:sequenced_assembly")
    event.create(MODID + "carved_rose_quartz")
    event.create(MODID + "incomplete_carved_rose_quartz", "create:sequenced_assembly")
    event.create(MODID + "ember_mechanism")
    event.create(MODID + "incomplete_ember_mechanism", "create:sequenced_assembly")
    event.create(MODID + "unprocessed_sulfurated_rubber")
    event.create(MODID + "sulfurated_rubber")
    event.create(MODID + "echo_shard_plate")
    event.create(MODID + "echo_mechanism")
    event.create(MODID + "incomplete_echo_mechanism", "create:sequenced_assembly")
    event.create(MODID + "echo_catalyst")
    event.create(MODID + "ineffective_echo_catalyst")
    event.create(MODID + "advanced_ember_mechanism")
    event.create(MODID + "incomplete_advanced_ember_mechanism", "create:sequenced_assembly")
    event.create(MODID + "advanced_sealed_mechanism")
    event.create(MODID + "incomplete_advanced_sealed_mechanism", "create:sequenced_assembly")
    event.create(MODID + "iron_ingot_with_echo_impurity")
    event.create(MODID + "duplicating_echo_shard", "create:sequenced_assembly")
    event.create(MODID + "paper_circuit_base")
    event.create(MODID + "incomplete_empty_pcb",'create:sequenced_assembly')
    event.create(MODID + "resistor")
    event.create(MODID + "incomplete_pcb",'create:sequenced_assembly')
    event.create(MODID + "plate_iron_compressed")
    event.create(MODID + "menril_mechanism")
    event.create(MODID + "incomplete_menril_mechanism", "create:sequenced_assembly")
    event.create(MODID + "incomplete_variable_transformer_output", "create:sequenced_assembly")
    event.create(MODID + "incomplete_variable_transformer_input", "create:sequenced_assembly")
    event.create(MODID + "caminite_capacitor_packet")
    event.create(MODID + "carbon_rod")
})