ItemEvents.modifyTooltips(event => {
    const MODID = "tse:"
    const solidChemicals = (id) => {
        event.add(MODID + id, [Text.translate("tooltip.tse." + id)])
    }
    const fluidChemicals = (id) => {
        event.add(MODID + id + "_bucket", [Text.translate("tooltip.tse." + id)])
    }
    //* 硬币
    event.add(MODID + "copper_coin", [Text.translate("tooltip.tse.copper_coin0"),Text.translate("tooltip.tse.copper_coin")])
    event.add(MODID + "compressed_iron_coin", [Text.translate("tooltip.tse.compressed_iron_coin0"),Text.translate("tooltip.tse.compressed_iron_coin")])
    event.add(MODID + "gold_coin", [Text.translate("tooltip.tse.gold_coin0"),Text.translate("tooltip.tse.gold_coin")])
    //* 变量卡 逻辑线缆
    event.add("integrateddynamics:variable",[
        Text.of(Text.translate("tooltip.tse.variable1")).white()
        .append(Text.of(Text.translate("tooltip.tse.variable2")).color("#aa00aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable3")).color("#f552f5"))
        .append(Text.of(Text.translate("tooltip.tse.variable4")).color("#aa0000"))
        .append(Text.of(Text.translate("tooltip.tse.variable5")).color("#e84e4f"))
        .append(Text.of(Text.translate("tooltip.tse.variable6")).color("#ffff55"))
        .append(Text.of(Text.translate("tooltip.tse.variable7")).color("#55ff55"))
        .append(Text.of(Text.translate("tooltip.tse.variable8")).color("#52f1f2"))
        .append(Text.of(Text.translate("tooltip.tse.variable9")).color("#00a5a5"))
        .append(Text.of(Text.translate("tooltip.tse.variable10")).color("#4f4de5"))
        .append(Text.of(Text.translate("tooltip.tse.variable11")).color("#0000aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable12")).color("#aa00aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable13")).white())
    ])
    event.add("integrateddynamics:cable",[
        Text.of(Text.translate("tooltip.tse.variable1")).white()
        .append(Text.of(Text.translate("tooltip.tse.variable2")).color("#aa00aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable3")).color("#f552f5"))
        .append(Text.of(Text.translate("tooltip.tse.variable4")).color("#aa0000"))
        .append(Text.of(Text.translate("tooltip.tse.variable5")).color("#e84e4f"))
        .append(Text.of(Text.translate("tooltip.tse.variable6")).color("#ffff55"))
        .append(Text.of(Text.translate("tooltip.tse.variable7")).color("#55ff55"))
        .append(Text.of(Text.translate("tooltip.tse.variable8")).color("#52f1f2"))
        .append(Text.of(Text.translate("tooltip.tse.variable9")).color("#00a5a5"))
        .append(Text.of(Text.translate("tooltip.tse.variable10")).color("#4f4de5"))
        .append(Text.of(Text.translate("tooltip.tse.variable11")).color("#0000aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable12")).color("#aa00aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable13")).white())
    ])
    //* 固体化学品
    solidChemicals("lead_monoxide")
    solidChemicals("lead_dioxide")
    solidChemicals("red_lead")
    solidChemicals("quicklime")
    solidChemicals("sodium_carbonate")
    solidChemicals("lead_carbonate")
    solidChemicals("lead_chloride")
    solidChemicals("lead_nitrate")
    solidChemicals("sodium_sulfide")
    solidChemicals("calcium_sulfide")
    solidChemicals("sodium_sulfate")
    solidChemicals("calcium_hydroxide")
    //* 流体化学品
    fluidChemicals("nitrogen")
    fluidChemicals("hydrogen")
    fluidChemicals("oxygen")
    fluidChemicals("chlorine")
    fluidChemicals("carbon_dioxide")
    fluidChemicals("carbon_monoxide")
    fluidChemicals("sulfur_trioxide")
    fluidChemicals("sulfur_dioxide")
    fluidChemicals("hydrogen_sulfide")
    fluidChemicals("ammonia")
    fluidChemicals("mathane")
    fluidChemicals("ethane")
    fluidChemicals("propane")
    fluidChemicals("butane")
    fluidChemicals("ethylene")
    fluidChemicals("propylene")
    fluidChemicals("butene")
    fluidChemicals("heavy_water")
    fluidChemicals("oleum")
    fluidChemicals("sulfuric_acid")
    fluidChemicals("nitric_acid")
    fluidChemicals("hydrochloric_acid")
    fluidChemicals("sodium_hydroxide")
    fluidChemicals("cold_sodium_hydroxide")
    fluidChemicals("ammonium_chloride")
    fluidChemicals("lead_nitrate")
    fluidChemicals("lead_chloride")
    fluidChemicals("sodium_bicarbonate")
    fluidChemicals("sodium_carbonate")
    fluidChemicals("sodium_hydrogen_sulfate")
    fluidChemicals("sodium_hypochlorite")
    fluidChemicals("methanol")
    fluidChemicals("octane")
    fluidChemicals("benzene")
    fluidChemicals("methylbenzene")
    fluidChemicals("molten_sulfur")
})