ItemEvents.modifyTooltips(event => {
    const MODID = "tse:"
    event.add(MODID + "copper_coin", [Text.translate("tooltip.tse.copper_coin0"),Text.translate("tooltip.tse.copper_coin")])
    event.add(MODID + "compressed_iron_coin", [Text.translate("tooltip.tse.compressed_iron_coin0"),Text.translate("tooltip.tse.compressed_iron_coin")])
    event.add(MODID + "gold_coin", [Text.translate("tooltip.tse.gold_coin0"),Text.translate("tooltip.tse.gold_coin")])
    event.add("integrateddynamics:variable",[
        Text.of(Text.translate("tooltip.tse.variable1")).white()
        .append(Text.of(Text.translate("tooltip.tse.variable2")).color("#aa00aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable3")).color("#f552f5"))
        .append(Text.of(Text.translate("tooltip.tse.variable4")).color("#aa0000"))
        .append(Text.of(Text.translate("tooltip.tse.variable5")).color("#e84e4f"))
        .append(Text.of(Text.translate("tooltip.tse.variable6")).color("#ffff55"))
        .append(Text.of(Text.translate("tooltip.tse.variable7")).color("#55ff55"))
        .append(Text.of(Text.translate("tooltip.tse.variable8")).color("#52f1f2"))
        .append(Text.of(Text.translate("tooltip.tse.variable9")).color("#00a5a5"))
        .append(Text.of(Text.translate("tooltip.tse.variable10")).color("#4f4de5"))
        .append(Text.of(Text.translate("tooltip.tse.variable11")).color("#0000aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable12")).color("#aa00aa"))
        .append(Text.of(Text.translate("tooltip.tse.variable13")).white())
    ])
})